import re

import unicodedata


def clean_text(text):

    # Task 1 Remove extra spaces

    text = re.sub(

        r'\s+',

        ' ',

        text

    )

    #2  Remove Blank Lines
    text = re.sub(
        r'\n\s*\n+',
        '\n\n',
        text
    )


    #3 Remove Page Nummbers 
    text = re.sub(
        r'(?m)^Page\s+\d+\s*$',
        '',
        text
    )

    #5 Remove Unwanted/special characters
    text = re.sub(
        r'[^\w\s.,;:!?()\-/]',
        '',
        text
    )

    #6 Fix broken sentences
    text = re.sub(
        r'(?<![.!?])\n(?!\n)',
        ' ',
        text
    )

    #7 Normalize Unicode characters
    text = unicodedata.normalize(
        "NFKC",
        text
    )

    #8 Removve Urls
    text = re.sub(
        r'https?://\S+|www\.\S+',
        '',
        text
    )

    #9 Remove Email Addresses
    text = re.sub(
        r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b',
        '',
        text
    )

    #10 OCR Cleanup
    text = re.sub(
        r'[_=|*#]{2,}',
        '',
        text
    )
    text = re.sub(
        r'\s+',
        ' ',
        text
    )

    #11 Removing Bolerplate
    boilerplate_patterns = [
        r'copyright\s*©?\s*\d{4}',
        r'all rights reserved',
        r'this document is confidential',
        r'generated by  .*'
    ]

    for pattern in boilerplate_patterns:
        text = re.sub(
            pattern,
            '',
            text,
            flags=re.IGNORECASE
        )


    #12 Preserve Important structure
    text = text.strip()

    text = re.sub(
        r' {2,}',
        '',
        text

    )

    return text.strip()